name: Build & Push escrin-runner Image
 
on:
  push:
    branches:
      - main
    paths:
      - 'pnpm-lock.yaml'
      - 'evm/abi/**'
      - 'worker/**'
      - '.github/workflows/runner-image.yaml'

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: worker/Dockerfile
          build-args: WORKERD_TAG=v1.20240304.0
          tags: |
            yourusername/escrin-runner:${{ github.sha }}
            yourusername/escrin-runner:latest
          push: true

  eif-build-and-push:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    container:
      image: amazonlinux:2023
    steps:
      - name: Install tools
        run: yum install aws-nitro-enclaves-cli aws-nitro-enclaves-cli-devel -y

      - name: Build EIF
        run: |
          nitro-cli build-enclave --docker-uri docker.io/yourusername/escrin-runner:latest --output-file escrin-runner.eif

      - name: Upload EIF to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: escrin-runner.eif
          path: escrin-runner.eif
